### ISSUE TITLE
On parsing error, report file causing the error

### ISSUE THREAD

**Issue by mikeeast** [x97mdr/pickles#54]
As I am having some people not using Visual Studio writing Specs, they make syntactic mistakes which leads to parsing errors.

I am getting an unhandled exception and would like to know which feature file that  caused the error. Or even better, the scenario.

This is the exception I'm getting:

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
    at Pickles.Parser.PicklesParser.CaptureAndStoreRemainingElements() in c:\dev\pickles\src\Pickles\Pickles\Parser\PicklesParser.cs:line 79
    at Pickles.Parser.PicklesParser.scenario(String keyword, String name, String description, Int32 line) in c:\dev\pickles\src\Pickles\Pickles\Parser\PicklesParser.cs:line 140
    at gherkin.lexer.i18n.EN.scan(String source)
    at gherkin.lexer.I18nLexer.scan(String source)
    at Pickles.FeatureParser.Parse(TextReader featureFileReader) in c:\dev\pickles\src\Pickles\Pickles\FeatureParser.cs:line 55
    at Pickles.FeatureParser.Parse(String filename) in c:\dev\pickles\src\Pickles\Pickles\FeatureParser.cs:line 41
    at Pickles.DirectoryCrawler.FeatureNodeFactory.Create(FileSystemInfo root, FileSystemInfo location) in c:\dev\pickles\src\Pickles\Pickles\DirectoryCrawler\FeatureNodeFactory.cs:line 57
    at Pickles.DirectoryCrawler.DirectoryTreeCrawler.Crawl(DirectoryInfo directory, IDirectoryTreeNode rootNode) in c:\dev\pickles\src\Pickles\Pickles\DirectoryCrawler\DirectoryTreeCrawler.cs:line 70
    at Pickles.DirectoryCrawler.DirectoryTreeCrawler.Crawl(DirectoryInfo directory, IDirectoryTreeNode rootNode) in c:\dev\pickles\src\Pickles\Pickles\DirectoryCrawler\DirectoryTreeCrawler.cs:line 77
    at Pickles.Runner.Run(IKernel kernel) in c:\dev\pickles\src\Pickles\Pickles\Runner.cs:line 38
    at Pickles.CommandLine.Program.Main(String[] args) in c:\dev\pickles\src\Pickles\Pickles.CommandLine\Program.cs:line 54

Thanks!

::m

**Comment by x97mdr** [comment]
Sorry, didn't get a chance to look at it tonight.  Going to be doing some serious coding this weekend though so I'll get it done then.

**Comment by mikeeast** [comment]
There's no stress from my part. Take your time.

**Comment by x97mdr** [comment]
I haven't compiled it into a binary yet but it should be fixed in this commit.  Can you try it and let me know?
