### ISSUE TITLE
Unhandled Exception while building HTML output

### ISSUE THREAD

**Issue by x97mdr** [x97mdr/pickles#87]
Help ... I'm getting the following Unhandled Exception when I run Pickles with these parameters

-f=.\features -o=c:\order-features

Reading features from c:\Users\stagr005\workspace\order-acceptance-tests\trunk\src\test\resources\features
Writing HTML to c:\order-features

<pre>
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Pickles.DirectoryCrawler.FeatureDirectoryTreeNode.get_Name() in c:\Users\stagr005\src\pickles\src\Pickles\Pickles\DirectoryCrawler\FeatureDirectory
   at Pickles.DocumentationBuilders.HTML.HtmlTableOfContentsFormatter.AddNodeForFile(XNamespace xmlns, Uri file, GeneralTree`1 childNode) in c:\Users\sta
ckles\DocumentationBuilders\HTML\HtmlTableOfContentsFormatter.cs:line 115
   at Pickles.DocumentationBuilders.HTML.HtmlTableOfContentsFormatter.BuildListItems(XNamespace xmlns, Uri file, GeneralTree`1 features) in c:\Users\stag
kles\DocumentationBuilders\HTML\HtmlTableOfContentsFormatter.cs:line 45
   at Pickles.DocumentationBuilders.HTML.HtmlTableOfContentsFormatter.AddNodeForDirectory(XNamespace xmlns, Uri file, GeneralTree`1 childNode) in c:\User
es\Pickles\DocumentationBuilders\HTML\HtmlTableOfContentsFormatter.cs:line 58
   at Pickles.DocumentationBuilders.HTML.HtmlTableOfContentsFormatter.BuildListItems(XNamespace xmlns, Uri file, GeneralTree`1 features) in c:\Users\stag
kles\DocumentationBuilders\HTML\HtmlTableOfContentsFormatter.cs:line 49
   at Pickles.DocumentationBuilders.HTML.HtmlTableOfContentsFormatter.Format(Uri file, GeneralTree`1 features, DirectoryInfo outputFolder) in c:\Users\st
ickles\DocumentationBuilders\HTML\HtmlTableOfContentsFormatter.cs:line 141
   at Pickles.DocumentationBuilders.HTML.HtmlDocumentFormatter.Format(IDirectoryTreeNode featureNode, GeneralTree`1 features, DirectoryInfo rootFolder) i
src\Pickles\Pickles\DocumentationBuilders\HTML\HtmlDocumentFormatter.cs:line 67
   at Pickles.HtmlDocumentationBuilder.<>c__DisplayClass1.<Build>b__0(IDirectoryTreeNode node) in c:\Users\stagr005\src\pickles\src\Pickles\Pickles\Docum
ntationBuilder.cs:line 99
   at NGenerics.Patterns.Visitor.ActionVisitor`1.Visit(T obj) in d:\Code\ngenerics\Source\NGenerics\Patterns\Visitor\ActionVisitor.cs:line 57
   at NGenerics.Patterns.Visitor.VisitorExtensions.AcceptVisitor[T](IEnumerable`1 enumerable, IVisitor`1 visitor) in d:\Code\ngenerics\Source\NGenerics\P
s.cs:line 39
   at Pickles.HtmlDocumentationBuilder.Build(GeneralTree`1 features) in c:\Users\stagr005\src\pickles\src\Pickles\Pickles\DocumentationBuilders\HTML\Html
   at Pickles.Runner.Run(IKernel kernel) in c:\Users\stagr005\src\pickles\src\Pickles\Pickles\Runner.cs:line 38
   at Pickles.CommandLine.Program.Main(String[] args) in c:\Users\stagr005\src\pickles\src\Pickles\Pickles.CommandLine\Program.cs:line 53
</pre>

**Comment by x97mdr** [comment]
It appears that you have some empty feature files in your directory tree.  I'll put up a fix ASAP
